import {Platform, StyleSheet} from 'react-native';

const myStyles = theme =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.backgroundColor,
      width: '100%',
    },
    listContent: {
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 24,
      flexGrow: 1,
    },
    filterRow: {
      flexDirection: 'row',
      gap: 8,
      paddingHorizontal: 16,
      paddingTop: 12,
    },
    filterPill: {
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderWidth: 1.5,
      borderColor: theme.headerBorder,
      borderRadius: 20,
      backgroundColor: 'transparent',
    },
    filterPillSelected: {
      borderColor: theme.background,
      borderWidth: 2,
      backgroundColor: theme.background + '15',
    },
    filterPillText: {
      fontFamily: 'Roboto-Regular',
      fontSize: 13,
      color: theme.font,
      fontWeight: '600',
    },
    filterPillTextSelected: {
      color: theme.background,
    },
    summaryText: {
      color: theme.gray,
      fontSize: 13,
      fontFamily: 'Roboto-Regular',
      marginTop: 8,
      marginBottom: 12,
      marginLeft: 4,
    },
    headerAddBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 12,
      paddingVertical: 6,
      marginRight: 8,
      borderRadius: 8,
      backgroundColor: theme.background + '18',
    },
    headerAddBtnText: {
      color: theme.background,
      fontSize: 14,
      fontFamily: 'Roboto-Medium',
      fontWeight: '600',
    },
    card: {
      width: '100%',
      borderRadius: 16,
      backgroundColor: theme.backgroundColor,
      borderWidth: 1,
      borderColor: theme.headerBorder + '40',
      padding: 16,
      marginBottom: 14,
      ...Platform.select({
        ios: {
          shadowColor: '#000',
          shadowOffset: {width: 0, height: 4},
          shadowOpacity: 0.06,
          shadowRadius: 10,
        },
        android: {
          elevation: 2,
        },
      }),
    },
    cardTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    avatarAndAmount: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      flexShrink: 1,
    },
    avatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: theme.background,
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarText: {
      color: '#FFFFFF',
      fontSize: 16,
      fontFamily: 'Roboto-Medium',
      fontWeight: '700',
    },
    amountText: {
      color: theme.font,
      fontSize: 16,
      fontFamily: 'Roboto-Medium',
      fontWeight: '700',
    },
    amountSubtitle: {
      color: theme.gray,
      fontSize: 12,
      fontFamily: 'Roboto-Regular',
      marginTop: 2,
    },
    statusBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 20,
    },
    statusBadgeText: {
      fontSize: 11,
      fontFamily: 'Roboto-Medium',
      fontWeight: '600',
    },
    divider: {
      height: 1,
      backgroundColor: theme.headerBorder + '30',
      marginVertical: 12,
    },
    detailRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: 8,
    },
    detailText: {
      color: theme.font,
      fontSize: 13,
      fontFamily: 'Roboto-Regular',
      flexShrink: 1,
    },
    recurrenceChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      alignSelf: 'flex-start',
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 20,
      marginTop: 10,
      backgroundColor: theme.background + '12',
    },
    recurrenceChipText: {
      color: theme.background,
      fontSize: 12,
      fontFamily: 'Roboto-Medium',
      fontWeight: '600',
    },
    failureBanner: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
      marginTop: 10,
      padding: 10,
      borderRadius: 10,
      backgroundColor: '#E5484D18',
    },
    failureBannerText: {
      flex: 1,
      color: '#E5484D',
      fontSize: 12,
      fontFamily: 'Roboto-Regular',
      lineHeight: 17,
    },
    footerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      gap: 10,
      marginTop: 14,
    },
    editButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: theme.background + '40',
    },
    editButtonText: {
      color: theme.background,
      fontSize: 13,
      fontFamily: 'Roboto-Medium',
      fontWeight: '600',
    },
    deleteButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: '#E5484D40',
    },
    deleteButtonText: {
      color: '#E5484D',
      fontSize: 13,
      fontFamily: 'Roboto-Medium',
      fontWeight: '600',
    },
    emptyContainer: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 40,
      paddingTop: 80,
    },
    emptyIconCircle: {
      width: 64,
      height: 64,
      borderRadius: 32,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.gray + '18',
      marginBottom: 16,
    },
    emptyTitle: {
      color: theme.font,
      fontSize: 16,
      fontFamily: 'Roboto-Medium',
      fontWeight: '700',
      marginBottom: 6,
      textAlign: 'center',
    },
    emptyText: {
      color: theme.gray,
      fontSize: 13,
      fontFamily: 'Roboto-Regular',
      textAlign: 'center',
      lineHeight: 19,
    },
  });

export default myStyles;
