ENV['SODIUM_ENABLED'] = '1'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

require Pod::Executable.execute_command('node', ['-p',
  "require.resolve('react-native-permissions/scripts/setup.rb', {paths: [process.argv[1]]})",
  __dir__]).strip

platform :ios, '16.0'
$VCEnableLocation = false
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
ENV['RCT_NEW_ARCH_ENABLED'] = '1'
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end


abstract_target 'coinswalletCommonPod' do
  setup_permissions(['Notifications'])

  config = use_native_modules!
  pod 'SDWebImage', '5.21.0'
  # AppCheckCore (pulled in by GoogleSignIn) is a Swift pod that imports these
  # Obj-C pods, which don't define modulemaps. Enable modular headers so they
  # can be imported when linking statically.
  pod 'GoogleUtilities', :modular_headers => true
  pod 'RecaptchaInterop', :modular_headers => true
  # permissions_path = '../node_modules/react-native-permissions/ios'
  # pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  # OpenSSL-Universal removed - QuickCrypto provides its own OpenSSL.xcframework
  pod 'TrustWalletCore', '3.2.9'
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true,
    :fabric_enabled => true
  )

    target 'coinswallet' do
        post_integrate do |installer|
           begin
            installer
           rescue => e
             Pod::UI.warn e
           end
         end
    end

    target 'kimlwallet' do
    end

    target 'OneSignalNotificationServiceExtension' do
      pod 'OneSignalXCFramework', '>= 5.0.0', '< 6.0'
    end

    target 'OneSignalNotificationServiceExtensionKimlWallet' do
      pod 'OneSignalXCFramework', '>= 5.0.0', '< 6.0'
    end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
       :mac_catalyst_enabled => false,
     # :ccache_enabled => true
    )
     bitcode_strip_path = `xcrun --find bitcode_strip`.chop!
       def strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
         framework_path = File.join(Dir.pwd, framework_relative_path)
         command = "#{bitcode_strip_path} #{framework_path} -r -o #{framework_path}"
         system(command)
       end
       installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1' # replace here with your minimum deployment
              config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
            end
        end

       framework_paths = [
         # OpenSSL-Universal removed - QuickCrypto provides its own OpenSSL
         # Bitcode is deprecated since Xcode 14 and no longer required for App Store
         "Pods/BugfenderSDK/BugfenderSDK.xcframework/ios-arm64/BugfenderSDK.framework/BugfenderSDK",
         "Pods/BugfenderSDK/BugfenderSDK.xcframework/ios-arm64_x86_64-maccatalyst/BugfenderSDK.framework/BugfenderSDK"
       ]

       framework_paths.each do |framework_relative_path|
         strip_bitcode_from_framework(bitcode_strip_path, framework_relative_path)
       end
  end
end
